name: coverity-scan
on:
  schedule:
    - cron: '30 4 0 * *' # Every Sunday at 4:30 UTC

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=insomniacslk%2Fdublin-traceroute" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share

      - name: Build with cov-build
        run: |
          mkdir build ;\
          cd build ;\
          cmake .. ;\
          export PATH=$PWD/cov-analysis-linux64/bin:$PATH ;\
          cov-build --dir cov-int make

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf dublin-traceroute.tgz cov-int
          curl \
            --form project=dublin-traceroute \
            --form token=$TOKEN \
            --form email=insomniacslk@users.noreply.github.com \
            --form file=@dublin-traceroute.tgz \
            --form version=trunk \
            --form description="`dublin-traceroute -v`" \
            https://scan.coverity.com/builds?project=insomniacslk%2Fdublin-traceroute
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
